// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhhmfVXC6lU8lQcZIWJsXBr7sYowNGiWo',
    appId: '1:709750327942:android:c3c963fabab057df655f07',
    messagingSenderId: '709750327942',
    projectId: 'muku2025',
    storageBucket: 'muku2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRNYsmJErY7fmh-H9GqtREn0PZu9UOWJY',
    appId: '1:276627586590:ios:a697eae3a7987793feb80f',
    messagingSenderId: '276627586590',
    projectId: 'muku-518b7',
    storageBucket: 'muku-518b7.firebasestorage.app',
    iosBundleId: 'com.example.muku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp2r1E7neUO5Tb4fuCsZrxM16n8Igtows',
    appId: '1:709750327942:ios:6014c658816a9b30655f07',
    messagingSenderId: '709750327942',
    projectId: 'muku2025',
    storageBucket: 'muku2025.firebasestorage.app',
    iosBundleId: 'com.example.muku',
  );

}